"""
Seed data — 50 realistic job listings across multiple categories.
"""
from datetime import datetime, timezone, timedelta
import random

SEED_JOBS = [
    {"title": "Senior Data Scientist", "company": "TechCorp AI", "description": "Build and deploy ML models for predictive analytics. Work with large datasets, develop NLP pipelines, and collaborate with product teams.", "required_skills": ["python", "machine learning", "tensorflow", "sql", "statistics"], "location": "Bangalore, India", "salary_range": {"min": 1800000, "max": 2800000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "Junior Python Developer", "company": "CodeWave Solutions", "description": "Write clean Python code for web applications. Assist in API development and testing. Learn from senior engineers.", "required_skills": ["python", "django", "rest api", "git"], "location": "Hyderabad, India", "salary_range": {"min": 500000, "max": 800000}, "experience_level": "junior", "job_type": "full-time"},
    {"title": "Full Stack Engineer", "company": "Innovatech", "description": "Build responsive web apps using React and Node.js. Design RESTful APIs, manage databases, and deploy to cloud.", "required_skills": ["javascript", "react", "node.js", "mongodb", "aws"], "location": "Remote", "salary_range": {"min": 1200000, "max": 2000000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "DevOps Engineer", "company": "CloudScale Inc", "description": "Manage CI/CD pipelines, containerize applications with Docker and Kubernetes. Automate infrastructure on AWS.", "required_skills": ["docker", "kubernetes", "aws", "terraform", "jenkins", "linux"], "location": "Pune, India", "salary_range": {"min": 1400000, "max": 2200000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "ML Engineer", "company": "DeepMind Labs", "description": "Research and implement deep learning models for computer vision. Optimize model performance for production.", "required_skills": ["python", "pytorch", "deep learning", "computer vision", "docker"], "location": "San Francisco, USA", "salary_range": {"min": 150000, "max": 220000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "Frontend Developer", "company": "PixelPerfect Design", "description": "Create beautiful, accessible UIs with React and TypeScript. Implement animations and responsive layouts.", "required_skills": ["react", "typescript", "css", "html", "figma"], "location": "Mumbai, India", "salary_range": {"min": 800000, "max": 1400000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Backend Engineer (Java)", "company": "FinServ Technologies", "description": "Build high-performance financial systems using Java and Spring Boot. Design microservices architecture.", "required_skills": ["java", "spring boot", "microservices", "postgresql", "kafka"], "location": "Chennai, India", "salary_range": {"min": 1500000, "max": 2500000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "Data Analyst", "company": "InsightCo Analytics", "description": "Analyze business data to uncover trends. Create dashboards and reports using SQL and visualization tools.", "required_skills": ["sql", "python", "tableau", "excel", "statistics"], "location": "Delhi, India", "salary_range": {"min": 600000, "max": 1000000}, "experience_level": "junior", "job_type": "full-time"},
    {"title": "Cloud Solutions Architect", "company": "AWS Partner Solutions", "description": "Design scalable cloud architectures for enterprise clients. Lead migration projects from on-prem to cloud.", "required_skills": ["aws", "azure", "cloud architecture", "terraform", "networking"], "location": "Remote", "salary_range": {"min": 2500000, "max": 4000000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "React Native Developer", "company": "MobileFirst Apps", "description": "Build cross-platform mobile applications using React Native. Integrate APIs and implement smooth animations.", "required_skills": ["react native", "javascript", "typescript", "mobile development", "rest api"], "location": "Bangalore, India", "salary_range": {"min": 1000000, "max": 1800000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "NLP Research Scientist", "company": "LangTech AI", "description": "Research and develop NLP models for text classification, sentiment analysis, and summarization.", "required_skills": ["python", "nlp", "transformers", "huggingface", "pytorch"], "location": "London, UK", "salary_range": {"min": 80000, "max": 120000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "QA Automation Engineer", "company": "TestPro Solutions", "description": "Design and implement automated test frameworks. Write end-to-end and integration tests for web apps.", "required_skills": ["selenium", "python", "pytest", "ci/cd", "rest api"], "location": "Noida, India", "salary_range": {"min": 700000, "max": 1200000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Product Manager", "company": "ScaleUp Ventures", "description": "Lead product strategy for B2B SaaS platform. Define roadmaps, prioritize features, and work with engineering.", "required_skills": ["product management", "agile", "data analysis", "stakeholder management", "ux"], "location": "Bangalore, India", "salary_range": {"min": 2000000, "max": 3500000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "Cybersecurity Analyst", "company": "SecureNet Corp", "description": "Monitor and respond to security incidents. Conduct vulnerability assessments and penetration testing.", "required_skills": ["cybersecurity", "networking", "linux", "siem", "penetration testing"], "location": "Hyderabad, India", "salary_range": {"min": 900000, "max": 1600000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "iOS Developer", "company": "AppForge Studios", "description": "Build native iOS applications using Swift and SwiftUI. Implement clean architecture patterns.", "required_skills": ["swift", "swiftui", "ios", "xcode", "core data"], "location": "Remote", "salary_range": {"min": 1200000, "max": 2000000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Data Engineer", "company": "DataPipeline Co", "description": "Build and maintain ETL pipelines. Design data warehouses and work with big data technologies.", "required_skills": ["python", "spark", "airflow", "sql", "aws", "kafka"], "location": "Pune, India", "salary_range": {"min": 1300000, "max": 2200000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "AI Research Intern", "company": "OpenAI Research", "description": "Assist in cutting-edge AI research. Implement and benchmark novel algorithms. Publish papers.", "required_skills": ["python", "machine learning", "deep learning", "mathematics", "research"], "location": "San Francisco, USA", "salary_range": {"min": 60000, "max": 80000}, "experience_level": "junior", "job_type": "contract"},
    {"title": "Site Reliability Engineer", "company": "HighAvail Systems", "description": "Ensure 99.99% uptime for distributed systems. Automate incident response and capacity planning.", "required_skills": ["linux", "kubernetes", "prometheus", "python", "networking", "docker"], "location": "Remote", "salary_range": {"min": 1600000, "max": 2800000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "UX Designer", "company": "DesignHub Creative", "description": "Design intuitive user experiences. Conduct user research, create wireframes and prototypes.", "required_skills": ["figma", "user research", "wireframing", "prototyping", "ux design"], "location": "Mumbai, India", "salary_range": {"min": 800000, "max": 1500000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Blockchain Developer", "company": "CryptoForge Labs", "description": "Develop smart contracts on Ethereum. Build decentralized applications and DeFi protocols.", "required_skills": ["solidity", "ethereum", "web3.js", "javascript", "blockchain"], "location": "Remote", "salary_range": {"min": 2000000, "max": 3500000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Go Backend Developer", "company": "SpeedServe Tech", "description": "Build high-concurrency backend services in Go. Design gRPC APIs and work with PostgreSQL.", "required_skills": ["go", "grpc", "postgresql", "docker", "microservices"], "location": "Bangalore, India", "salary_range": {"min": 1500000, "max": 2500000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Technical Writer", "company": "DocuTech Solutions", "description": "Write API documentation, tutorials, and developer guides. Simplify complex technical concepts.", "required_skills": ["technical writing", "api documentation", "markdown", "git"], "location": "Remote", "salary_range": {"min": 600000, "max": 1000000}, "experience_level": "junior", "job_type": "part-time"},
    {"title": "Database Administrator", "company": "DataGuard Systems", "description": "Manage and optimize MongoDB and PostgreSQL databases. Implement backup strategies and security.", "required_skills": ["mongodb", "postgresql", "database optimization", "linux", "backup"], "location": "Chennai, India", "salary_range": {"min": 1000000, "max": 1800000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Computer Vision Engineer", "company": "VisionAI Labs", "description": "Develop image recognition and object detection models. Work with cameras and edge devices.", "required_skills": ["python", "opencv", "deep learning", "computer vision", "tensorflow"], "location": "Bangalore, India", "salary_range": {"min": 1500000, "max": 2500000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Rust Systems Engineer", "company": "LowLatency Corp", "description": "Build high-performance systems software in Rust. Focus on memory safety and zero-cost abstractions.", "required_skills": ["rust", "systems programming", "linux", "networking", "c++"], "location": "Remote", "salary_range": {"min": 2000000, "max": 3500000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "Django Full Stack Developer", "company": "WebCraft Studios", "description": "Build web applications using Django and Vue.js. Implement payment integrations and user auth.", "required_skills": ["python", "django", "vue.js", "postgresql", "rest api", "html", "css"], "location": "Hyderabad, India", "salary_range": {"min": 900000, "max": 1500000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "MLOps Engineer", "company": "ModelDeploy AI", "description": "Build ML model deployment pipelines. Manage model versioning, monitoring, and A/B testing infrastructure.", "required_skills": ["python", "mlflow", "docker", "kubernetes", "aws", "machine learning"], "location": "Remote", "salary_range": {"min": 1800000, "max": 3000000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "Embedded Systems Engineer", "company": "IoT Innovations", "description": "Develop firmware for IoT devices. Program microcontrollers and implement communication protocols.", "required_skills": ["c", "c++", "embedded systems", "rtos", "iot", "hardware"], "location": "Pune, India", "salary_range": {"min": 800000, "max": 1400000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Angular Frontend Developer", "company": "EnterpriseUI Co", "description": "Build enterprise web dashboards using Angular. Implement complex forms, charts, and real-time updates.", "required_skills": ["angular", "typescript", "rxjs", "html", "css", "rest api"], "location": "Delhi, India", "salary_range": {"min": 900000, "max": 1600000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Platform Engineer", "company": "InfraScale Technologies", "description": "Build and maintain internal developer platform. Create reusable templates and CI/CD workflows.", "required_skills": ["kubernetes", "terraform", "aws", "python", "github actions", "docker"], "location": "Bangalore, India", "salary_range": {"min": 1600000, "max": 2800000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "Salesforce Developer", "company": "CRM Solutions Inc", "description": "Customize Salesforce CRM. Build Apex triggers, Lightning components, and integrations.", "required_skills": ["salesforce", "apex", "lightning", "soql", "javascript"], "location": "Mumbai, India", "salary_range": {"min": 1000000, "max": 1800000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Unity Game Developer", "company": "GameForge Studios", "description": "Develop 3D games using Unity and C#. Implement game mechanics, physics, and multiplayer features.", "required_skills": ["unity", "c#", "3d graphics", "game design", "multiplayer"], "location": "Remote", "salary_range": {"min": 800000, "max": 1500000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "ETL Developer", "company": "DataFlow Solutions", "description": "Design and implement ETL processes for data integration. Work with various data sources and formats.", "required_skills": ["sql", "python", "etl", "data warehousing", "airflow"], "location": "Noida, India", "salary_range": {"min": 800000, "max": 1400000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Scrum Master", "company": "AgileWorks Consulting", "description": "Facilitate agile ceremonies. Coach teams on Scrum practices and remove impediments.", "required_skills": ["scrum", "agile", "jira", "facilitation", "coaching"], "location": "Bangalore, India", "salary_range": {"min": 1200000, "max": 2000000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "AI/ML Product Manager", "company": "SmartAI Products", "description": "Define and drive AI-powered product features. Bridge technical ML teams and business stakeholders.", "required_skills": ["product management", "machine learning", "data analysis", "agile", "communication"], "location": "Remote", "salary_range": {"min": 2500000, "max": 4000000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "PHP Laravel Developer", "company": "WebDev Factory", "description": "Build web applications using PHP Laravel. Implement e-commerce features and content management.", "required_skills": ["php", "laravel", "mysql", "javascript", "html", "css"], "location": "Jaipur, India", "salary_range": {"min": 500000, "max": 900000}, "experience_level": "junior", "job_type": "full-time"},
    {"title": "Kubernetes Administrator", "company": "ContainerOps Ltd", "description": "Manage production Kubernetes clusters. Implement RBAC, network policies, and monitoring.", "required_skills": ["kubernetes", "docker", "helm", "prometheus", "grafana", "linux"], "location": "Hyderabad, India", "salary_range": {"min": 1400000, "max": 2400000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "Flutter Mobile Developer", "company": "CrossPlatform Apps", "description": "Build beautiful cross-platform mobile apps using Flutter and Dart. Integrate Firebase services.", "required_skills": ["flutter", "dart", "firebase", "mobile development", "rest api"], "location": "Remote", "salary_range": {"min": 900000, "max": 1600000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "SAP Consultant", "company": "Enterprise Solutions Group", "description": "Implement and customize SAP modules. Configure business processes and train end users.", "required_skills": ["sap", "abap", "business process", "erp", "consulting"], "location": "Mumbai, India", "salary_range": {"min": 1500000, "max": 2500000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "Generative AI Engineer", "company": "GenAI Startup", "description": "Build applications using LLMs. Implement RAG pipelines, prompt engineering, and fine-tuning.", "required_skills": ["python", "langchain", "openai", "vector databases", "nlp", "machine learning"], "location": "Remote", "salary_range": {"min": 2000000, "max": 3500000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Network Engineer", "company": "NetConnect Solutions", "description": "Design and maintain enterprise networks. Configure routers, switches, and firewalls.", "required_skills": ["networking", "cisco", "firewalls", "tcp/ip", "linux"], "location": "Delhi, India", "salary_range": {"min": 700000, "max": 1200000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Power BI Analyst", "company": "BI Insights Corp", "description": "Create interactive dashboards and reports using Power BI. Perform data modeling and DAX calculations.", "required_skills": ["power bi", "dax", "sql", "data modeling", "excel"], "location": "Pune, India", "salary_range": {"min": 600000, "max": 1100000}, "experience_level": "junior", "job_type": "full-time"},
    {"title": "AWS Cloud Engineer", "company": "CloudNative Solutions", "description": "Design and implement AWS infrastructure. Build serverless applications and manage cloud costs.", "required_skills": ["aws", "lambda", "cloudformation", "python", "s3", "dynamodb"], "location": "Bangalore, India", "salary_range": {"min": 1400000, "max": 2400000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Automation Test Lead", "company": "QualityFirst Tech", "description": "Lead test automation team. Define test strategies, frameworks, and ensure quality across releases.", "required_skills": ["selenium", "java", "test automation", "ci/cd", "team leadership"], "location": "Chennai, India", "salary_range": {"min": 1500000, "max": 2500000}, "experience_level": "senior", "job_type": "full-time"},
    {"title": "Ruby on Rails Developer", "company": "RailsForge Co", "description": "Build and maintain Ruby on Rails web applications. Implement RESTful APIs and background jobs.", "required_skills": ["ruby", "rails", "postgresql", "redis", "rest api"], "location": "Remote", "salary_range": {"min": 1000000, "max": 1800000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Business Intelligence Engineer", "company": "DataViz Solutions", "description": "Build data pipelines and create BI dashboards. Work with stakeholders to define KPIs.", "required_skills": ["sql", "python", "tableau", "data warehousing", "etl"], "location": "Bangalore, India", "salary_range": {"min": 1200000, "max": 2000000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Technical Support Engineer", "company": "SupportPro Systems", "description": "Provide L2/L3 technical support for enterprise software. Troubleshoot and resolve complex issues.", "required_skills": ["troubleshooting", "linux", "networking", "sql", "communication"], "location": "Noida, India", "salary_range": {"min": 500000, "max": 900000}, "experience_level": "junior", "job_type": "full-time"},
    {"title": "Hadoop Big Data Engineer", "company": "BigData Corp", "description": "Build and manage Hadoop clusters. Develop MapReduce jobs and Hive queries for large-scale data processing.", "required_skills": ["hadoop", "hive", "spark", "java", "linux", "data engineering"], "location": "Hyderabad, India", "salary_range": {"min": 1200000, "max": 2000000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "FastAPI Backend Developer", "company": "PythonCloud Inc", "description": "Build async REST APIs using FastAPI. Implement MongoDB integration, Redis caching, and event queues.", "required_skills": ["python", "fastapi", "mongodb", "redis", "docker", "rest api"], "location": "Remote", "salary_range": {"min": 1200000, "max": 2200000}, "experience_level": "mid", "job_type": "full-time"},
    {"title": "Solutions Architect", "company": "TechAdvisors Global", "description": "Design end-to-end technology solutions for enterprise clients. Lead architecture reviews and POCs.", "required_skills": ["cloud architecture", "microservices", "system design", "aws", "communication"], "location": "Bangalore, India", "salary_range": {"min": 3000000, "max": 5000000}, "experience_level": "senior", "job_type": "full-time"},
]


def get_seed_jobs():
    """Return seed jobs with randomized posted dates."""
    jobs = []
    for i, job in enumerate(SEED_JOBS):
        job_copy = dict(job)
        days_ago = random.randint(1, 60)
        job_copy["posted_at"] = datetime.now(timezone.utc) - timedelta(days=days_ago)
        jobs.append(job_copy)
    return jobs
